# Generated by Django 5.2.4 on 2025-07-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondata',
            name='name',
            field=models.CharField(max_length=49),
        ),
    ]
